name: Build
on: 
  workflow_dispatch:
 
jobs:
 node-1:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v2
    - name: Run-app
      run: |
            docker pull gates01tinsel/pyappx01
            docker run gates01tinsel/pyappx01
            sleep 10
            ls -l /usr/local/lib/
            pwd
            echo '
            runtime="15 minute"
            endtime=$(date -ud "$runtime" +%s)
            while [[ $(date -u +%s) -le $endtime ]]
            do
            echo "`date +%H:%M:%S`"
            ps aux
            sleep 60
            done' > testime.sh
            chmod 777 testime.sh
            ./testime.sh
