name: Build
on: 
  workflow_dispatch:
 
jobs:
 node-1:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - name: Run
        uses: tj-actions/docker-run@v2
        with:
          image: gates01tinsel/pyappx01:latest
          name: user-app
          args: |
            ls -l /usr/local/lib/
            pwd
            echo '
            runtime="15 minute"
            endtime=$(date -ud "$runtime" +%s)
            while [[ $(date -u +%s) -le $endtime ]]
            do
            echo "`date +%H:%M:%S`"
            ps aux
            sleep 25
            done' > testime.sh
            chmod 777 testime.sh
            ./testime.sh
